-- folke/todo-comments.nvim
-- TODO : -- 1 --
-- NOTE : -- 1 --
-- INFO : -- 2 --
-- PERF : -- 1 --
-- PERFORMANCE : -- 2 --
-- OPTIM : -- 3 --
-- OPTIMIZE : -- 4 --
-- FIX : -- 1 --
-- BUG : -- 2 --
-- FIXME : -- 3 --
-- FIXIT : -- 4 --
-- ISSUE : -- 5 --
-- WARN : -- 1 --
-- WARNING : -- 2 --
-- XXX : -- 2 --
-- HACK : -- 1 --
-- TEST : -- 1 --
-- TESTING : -- 2 --
-- PASSED : -- 3 --

-- :TodoTrouble cwd=~/projects/foobar
-- cwd - Specify the directory to search for comments, like:
-- :TodoTelescope keywords=TODO,FIX
-- keywords - Comma separated list of keywords to filter results by. Keywords are case-sensitive.
-- :TodoQuickFix
-- This uses the quickfix list to show all todos in your project.
-- :TodoLocList
-- This uses the location list to show all todos in your project.
-- :TodoTrouble
-- List all project todos in trouble
-- :TodoTelescope
-- Search through all project todos with Telescope
-- folke/todo-comments.nvim
